name: CoreManager
version: 1.0-SNAPSHOT
main: com.zhuerta.coremanager.CoreManager
description: Un plugin modular para Velocity con anuncios automáticos y más.
authors: [zHuerta]
dependencies:
  - name: LuckPerms
    optional: false
commands:
  coremanager:
    description: Comando principal de CoreManager
    aliases: [cm]
    usage: /coremanager <reload|list>
permissions:
  coremanager.reload:
    description: Permite usar el subcomando /coremanager reload para recargar el plugin.
    default: op
  coremanager.list:
    description: Permite usar el subcomando /coremanager list para ver la lista de anuncios.
    default: op
  coremanager.broadcast:
    description: Permite usar el subcomando /coremanager broadcast para enviar anuncios personalizados.
    default: op